title: Bayesian Optimization Book
author: Roman Garnett
email: contact@bayesoptbook.com
description: Copyright 2023 Roman Garnett, published by Cambridge University Press
baseurl: ""
url: "https://bayesoptbook.com/"
github_username: bayesoptbook
logo: /assets/cover.png

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

github: [metadata]